server:
  port: 8080
  servlet:
    context-path: /scaffolds/
    encoding:
      charset: UTF-8

spring:
  datasource:
    name: mysql
    url: jdbc:mysql://localhost:3306/sscs?useSSL=true&characterEncoding=UTF-8&serverTimezone=Asia/Shanghai
    username: root
    password: root
    driver-class-name: com.mysql.cj.jdbc.Driver
    type: com.alibaba.druid.pool.DruidDataSource
    filters: stat
    maxActive: 20
    initialSize: 20
    maxWait: 60000
    minIdle: 10
    timeBetweenEvictionRunsMillis: 60000
    minEvictableIdleTimeMillis: 300000
    validationQuery: select 'x'
    testWhileIdle: true
    testOnBorrow: false
    testOnReturn: false
    poolPreparedStatements: true
    maxOpenPreparedStatements: 20

  jackson:
    default-property-inclusion: non_null
    date-format: yyyy-MM-dd HH:mm:ss
    time-zone: GMT+8

  # 模板配置
  thymeleaf:
    cache: false
    mode: HTML

  mvc:
    view:
      prefix: classpath:/templates/
      suffix: .html
    static-path-pattern: /static/**

  shiro:
    # 允许匿名访问的url地址
    ignoreAuthUrl:
      - /static/**
      - /templates/error/**

# mybatis-plus配置
mybatis-plus:
  mapper-locations: classpath:mapping/*.xml
  type-aliases-package: com.wto.scaffolds.model
  # 是否开启大小写
  configuration:
    map-underscore-to-camel-case: false

# 是否开启swagger
swagger:
  show: true
  basePackage: com.wto.scaffolds
  title: 脚手架 接口文档